### ISSUE TITLE
Canal Sic Kids a transmitir Sic

### ISSUE THREAD

**Issue by PedroMD** [myIPTVChannels/lists#15]
O canal Sic Kids, da secção Infantil está a transmitir a Sic normal. Podem ver isso, sff? Não encontro este canal em mais lado nenhum a não ser aqui, e mesmo aqui a transmissão está errada...

**Comment by adrianoafonso** [comment]
Este projecto fundamente-se na partilha, não nos pedidos de canais. Podes ajudar a procurar e colocar aqui uma ligação para que a possamos corrigir. Visto que tens conta, podes tu mesmo apresentar a correcção.

**Comment by PedroDank** [comment]
Porque é que a malta vê tudo como uma crítica?! Eu apenas vim avisar -
podiam não ter reparado no erro. Se tivesse uma fonte, claro que a teria
partilhado. Até à data, está era única lista que acreditava ter este canal.
Se não tem, deviam remover, até se encontrar uma outra fonte...

Nem toda malta da internet é troll. E tratarem toda a gente como tal, só
alimenta esse tipo de comportamento.

Obrigado e continuação de bom trabalho! Se puder ajudar, ajudo.
Adriano Afonso <notifications@github.com> escreveu em qui, 25/02/2016 às
19:48 :

**Comment by adrianoafonso** [comment]
Olá Pedro.
Como deves calcular, sendo um projecto comunitário, cabe a cada um ir actualizando, alterando, inserindo. Não entendas como critica, apenas respondi literalmente. Trabalho em SL há anos e só neste projecto recebo este tipo de "issues". Como deves calcular, "irrita". Nada pessoal.
Só alimenta a quem não percebe os fundamentos da colaboração.
Já és Colab? queres que te coloque como tal?
