### ISSUE TITLE
O grupo funciona?

### ISSUE THREAD

**Issue by RuiJMoreira** [myIPTVChannels/lists#16]
O grupo do Facebook (https://www.facebook.com/groups/listasiptv/) está a funcionar?
É que não consigo aceder - http://prntscr.com/cnhhg7

**Comment by adrianoafonso** [comment]
Olá Rui, sim ainda está a funcionar, as colaborações é que baixaram muito!
Encontra-me por lá e fala comigo para tentar perceber o que se passa com a tua conta!
Pode ter sido banida por alguma razão!!

**Comment by RuiJMoreira** [comment]
Pois, mas não consigo aceder...
