### ISSUE TITLE
Site cxtv.biz - Como obter os links

### ISSUE THREAD

**Issue by RuiJMoreira** [myIPTVChannels/lists#17]
Este novo site que anda por aí dá acesso a muitos canais nacionais em HD!
Deixo aqui as instruções de como aceder aos links **http://**:

**1º** Abrimos a página do canal em questão (Exemplo SPORT TV 1) - http://prntscr.com/crtalp;
**2º** Após abrir a página clicamos em ver o código fonte - http://prntscr.com/crtbbf;
**3º** No código fonte procuramos por um script semelhante a este - http://prntscr.com/crtbmp;
**4º** Agora temos o link do canal aqui (Em frente a "src:") - http://prntscr.com/crtc7w.

Não coloquei os links nas listas porque não sei se funcionam bem, gostaria que testassem e dessem feedback.

**Comment by martunis01** [comment]
e qual é o link do site?
assim é difícil ir la ter

No dia 9 de outubro de 2016 às 21:11, Rui Moreira <notifications@github.com>
escreveu:

**Comment by RuiJMoreira** [comment]
Conforme foi indicado aqui - http://prntscr.com/cskmzr, o link é - cxtv.biz

**Comment by adrianoafonso** [comment]
Aqueles que queria (os não generalistas) já estão quase todos em baixo....

**Comment by sheikr** [comment]
Isto quanto muito devia estar na Wiki. Obrigado pelo link.
